language: cpp
compiler: gcc-4.8
before_install:
  - sudo apt-get update
  - sudo apt-get -qq install g++-4.8
before_script:
  - mkdir obj
  - make
  - cd tests
script:
  - ./mktest
after_failure:
  - python printCSV.py